name: JunkWunk
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

    # Firebase packages
  firebase_auth: ^5.3.4
  firebase_auth_web: ^5.13.3
  firebase_core: ^3.9.0
  firebase_storage: ^12.3.7
  cloud_firestore: ^5.6.0

  # Authentication
  google_sign_in: ^6.2.2

  # UI and Icons
  cupertino_icons: ^1.0.8
  flutter_login: ^4.2.1

  # State Management (if needed)
  provider: ^6.1.2

  connectivity_plus: ^6.1.3
  image_picker: ^1.1.2
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  path: ^1.9.0
  http: ^1.3.0
  universal_html: ^2.2.4
  app_settings: ^5.2.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  smooth_page_indicator: ^1.2.1
  flutter_svg: ^2.1.0
  lottie: ^3.3.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/credentials/service_account.json
    - assets/default_picture.jpg
